- hosts: localhost
  become: yes
  tasks: 
  - name: Install a list of packages
    apt:
      pkg:
        - gcc
        - make
        - perl
        - git
        - gitk
        - curl
        - mc
        - vlc
        - telegram-desktop
        - obs-studio
        - flameshot
